services:
  - type: web
    name: GOF_DB
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
    - key: POSTGRES_USER
      value: gorgui02
    - key: POSTGRES_PASSWORD
      value: gorgui02
    - key: POSTGRES_DB
      value: GOF_DB
    - key: POSTGRES_HOST_AUTH_METHOD
      value: trust

    ports:
      - 5432
