app = "gof-db"

[build]
  dockerfile = "Dockerfile"

[env]
  POSTGRES_USER = "gorgui02"
  POSTGRES_PASSWORD = "gorgui02"
  POSTGRES_DB = "GOF_DB"

[[services]]
  internal_port = 5432
  protocol = "tcp"

  [[services.ports]]
    port = 5432
